from django.contrib import admin
from django.urls import path, re_path
from . import views
from . import ajax
from . import student_info_check
from django.views.decorators.csrf import csrf_exempt
app_name = 'adminpage'
urlpatterns = [
    path('', views.adminpage, name = "adminpagee"),
    path('category/', views.getCategory, name = "category"),
    path('categorydetail/<int:category_id>/', views.getCategoryDetail, name='categorydetail'),
    path('get-post-data/<int:post_id>/', views.get_post_data, name='get_post_data'),

    path('phongban/', views.get_PB, name="phongban" ),
    path('cctc/<int:pb_id>/', views.get_CCTC, name="CCTC"),
    path('forum/', views.forum_manage, name='forum_manage'),
    path('admission/', views.get_Admission, name="admission"),
    path('letter/<int:admission_id>/', views.get_Letter, name="letter"),
    path('exam-registration/', views.get_ExamRegistration, name="exam_registration"),
    path('registration-history/<int:registration_id>/', views.view_registration_history, name='registration_history'),
    path('export-exam-registrations/', views.export_exam_registrations, name='export_exam_registrations'),
    path('import-students/', views.import_students_excel, name="import_students_excel"),
    path('save-imported-students/', views.save_imported_students, name="save_imported_students"),
    # Kiểm tra thông tin học viên (THPT)
    path('student-info/', student_info_check.student_info_manage, name='student_info_manage'),
    path('student-info/import-excel/', student_info_check.student_info_import_excel, name='student_info_import_excel'),
    path('student-info/import-preview/', student_info_check.student_info_import_preview, name='student_info_import_preview'),
    path('student-info/save-imported/', student_info_check.student_info_save_imported, name='student_info_save_imported'),
    path('student-info/export-excel/', student_info_check.student_info_export_excel, name='student_info_export_excel'),
    path(
        'student-info/verification/<str:student_code>/',
        student_info_check.student_info_verification_json,
        name='student_info_verification_json',
    ),
    path(
        'student-info/history/<str:student_code>/',
        student_info_check.student_info_verification_history,
        name='student_info_verification_history',
    ),
    # path('get_role/', ajax.get_role, name="get_role"),
    # path('course/', views.course, name = "course"),
    # path('get_course/', ajax.get_course, name="get_course"),
    # path('get_course_update/', ajax.get_course_update, name="get_course_update"),
    # # path('coursedetail/<int:course_id>/', views.coursedetail, name="coursedetail"),
    # # path('get_chapter/', ajax.get_chapter, name="get_chapter"),
    # # path('chapterdetail/<int:chapter_id>/<int:course_id>/', views.chapterdetail, name="chapterdetail"),
    # # path('get_chapter_update/', ajax.get_chapter_update, name="get_chapter_update"),
    # # path('get_lesson/', ajax.get_lesson, name="get_lesson"),
    # # path('lessondetail/<int:chapter_id>/<int:lesson_id>/', views.lessondetail, name="lessondetail"),
    # # path('get_lesson_update/', ajax.get_lesson_update, name="get_lesson_update"),
    # path('get_activity/', ajax.get_activity, name="get_activity"),
    # path('activity/<int:course_id>/', views.activity, name="activity"),
    # path('activitydetail/<int:activity_id>/', views.activitydetail, name="activitydetail"),
    # path('check_activity/', ajax.check_activity, name="check_activity"),
    # path('get_data_activity/', ajax.get_data_activity, name="get_data_activity"),
    # path('Phaser/',views.Phaser,name="Phaser"),
    # path('posttype/', views.posttype, name="posttype"),
    # path('get_posttype/', ajax.get_posttype, name="get_posttype"),
    # path('forumpost/<int:posttype_id>/', views.forumpost, name='forumpost'),
    # path('forumanswer/<int:post_id>/', views.forumanswer, name="forumanswer"),
    # path('submit_approved/', ajax.submit_approved, name="submit_approved"),
    # path('delete_comment/', ajax.delete_comment, name="delete_comment"),
    # path('change_active/', ajax.change_active, name="change_active"),
    # path('upload_image/',csrf_exempt(views.upload_image), name='upload_image'),

    # API endpoints for address data
    path('api/provinces/', ajax.get_provinces, name='get_provinces'),
    path('api/districts/<str:province_code>/', ajax.get_districts, name='get_districts'),
    path('api/wards/<str:district_code>/', ajax.get_wards, name='get_wards'),
    path('export-approved-admissions/', views.export_approved_admissions, name='export_approved_admissions'),
    path('attendance-pivot/', views.attendance_pivot, name='attendance_pivot'),
    path('import-dsgv/', views.import_dsgv_excel, name='import_dsgv_excel'),
    path('import-dsl/', views.import_dsl_excel, name='import_dsl_excel'),
    path('import-tkb/', views.import_tkb_excel, name='import_tkb_excel'),
    path('delete-schedule-version/', views.delete_schedule_version, name='delete_schedule_version'),
    path('clear-attendance-data/', views.clear_attendance_data, name='clear_attendance_data'),
    path('api/save-attendance-cell/', ajax.save_attendance_cell, name='save_attendance_cell'),
    path('api/save-attendance-cells-bulk/', ajax.save_attendance_cells_bulk, name='save_attendance_cells_bulk'),
    path('api/save-attendance-excluded-days/', ajax.save_attendance_excluded_days, name='save_attendance_excluded_days'),
    path('export-attendance-excel/', views.export_attendance_excel, name='export_attendance_excel'),
    # Sắp xếp phòng thi (tối giản)
    path('exam-room/sort/', views.exam_room_sort_dashboard, name='exam_room_sort_dashboard'),
    path('exam-room/move-students/', views.exam_room_move_students, name='exam_room_move_students'),
    path('exam-room/export-excel/', views.exam_room_export_excel, name='exam_room_export_excel'),
    path('exam-room/reassign-sbd/', views.exam_room_reassign_sbd, name='exam_room_reassign_sbd'),
    path('exam-room/delete-all/', views.exam_room_delete_all_students, name='exam_room_delete_all_students'),
    path('exam-room/delete-student/<str:student_code>/', views.exam_room_delete_student, name='exam_room_delete_student'),
    path('exam-room/import-students/', views.exam_room_import_students, name='exam_room_import_students'),
    path('exam-room/import-phongthi/', views.exam_room_import_phongthi, name='exam_room_import_phongthi'),
    path('exam-room/save-phongthi-import/', views.exam_room_save_phongthi_import, name='exam_room_save_phongthi_import'),
    path('exam-room/phongthi-mau.xlsx', views.exam_room_phongthi_template, name='exam_room_phongthi_template'),
    path('exam-room/save-imported-students/', views.exam_room_save_imported_students, name='exam_room_save_imported_students'),
    path('exam-room/toggle-integration/<str:student_code>/', views.exam_room_toggle_integration, name='exam_room_toggle_integration'),
    path('exam-room/manage/', views.exam_room_manage, name='exam_room_manage'),
    path('exam-room/bulk-export-excel/', views.exam_room_bulk_export_excel, name='exam_room_bulk_export_excel'),
    path('exam-room/delete-all-rooms/', views.exam_room_delete_all_rooms, name='exam_room_delete_all_rooms'),
    path('exam-room/delete/<int:room_id>/', views.exam_room_delete, name='exam_room_delete'),
    path('exam-room/update/<int:room_id>/', views.exam_room_update, name='exam_room_update'),
    path('exam-room/<int:room_id>/export-excel/', views.exam_room_detail_export_excel, name='exam_room_detail_export_excel'),
    path('exam-room/<int:room_id>/', views.exam_room_detail, name='exam_room_detail'),
    # Sổ đầu bài số (Quản lý)
    path('so-dau-bai/', views.journal_manager_dashboard, name='journal_manager_dashboard'),
    path('so-dau-bai/mon/<int:journal_id>/', views.journal_subject_detail, name='journal_subject_detail'),
    path('so-dau-bai/mon/<int:journal_id>/tuan/<int:week_number>/', views.journal_week_summary, name='journal_week_summary'),
    path('so-dau-bai/mon/<int:journal_id>/tuan/<int:week_number>/export-missing/', views.journal_week_missing_export, name='journal_week_missing_export'),
    path('so-dau-bai/mon/<int:journal_id>/export-excel/', views.journal_export_excel, name='journal_export_excel'),
    path('so-dau-bai/export-excel-tuan/', views.journal_export_excel_all_week, name='journal_export_excel_all_week'),
    path('so-dau-bai/import-dsgv/', views.import_journal_dsgv, name='import_journal_dsgv'),
    path('so-dau-bai/import-dsl/', views.import_journal_dsl, name='import_journal_dsl'),
    path('so-dau-bai/thong-ke-chua-ghi/export/', views.journal_missing_all_subjects_week_export, name='journal_missing_all_subjects_week_export'),
    path('so-dau-bai/thong-ke/export/', views.journal_thong_ke_export, name='journal_thong_ke_export'),
]
urlpatterns += [
    path('import-cccd-excel/', views.import_cccd_excel, name='import_cccd_excel'),
    path('delete-cccd-excel/', views.delete_cccd_excel, name='delete_cccd_excel'),
    path('update-conduct-excel/', views.update_conduct_excel, name='update_conduct_excel'),
    path('export-conduct-template/', views.export_conduct_template, name='export_conduct_template'),
]