# Generated by Django 4.2.7 on 2024-11-19 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('content', models.TextField(blank=True, max_length=100)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('image_file', models.ImageField(blank=True, upload_to='image')),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.category')),
            ],
        ),
    ]
