# Generated by Django 4.2.7 on 2024-11-20 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_remove_post_pdf_file_pdffile'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.DeleteModel(
            name='PDFFile',
        ),
    ]
