# Generated by Django 4.2.7 on 2024-11-21 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_post_pdf_file_delete_pdffile'),
    ]

    operations = [
        migrations.CreateModel(
            name='NamhHoc',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('namhoc', models.IntegerField(blank=True)),
                ('enable', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='LichCongTac',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('pdf_file', models.FileField(blank=True, null=True, upload_to='pdfs/')),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('namhoc', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.namhhoc')),
            ],
        ),
    ]
