# Generated by Django 4.2.7 on 2024-11-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_namhhoc_lichcongtac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namhhoc',
            name='namhoc',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
