# Generated by Django 4.2.7 on 2024-11-23 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_alter_namhhoc_namhoc'),
    ]

    operations = [
        migrations.CreateModel(
            name='GV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('role1', models.CharField(blank=True, max_length=50, null=True)),
                ('role2', models.CharField(blank=True, max_length=50, null=True)),
                ('sex', models.BooleanField(default=True)),
                ('chuyenmon', models.CharField(blank=True, max_length=50, null=True)),
                ('namsinh', models.DateField(auto_now_add=True, null=True)),
                ('bac', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhongBan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('enable', models.BooleanField(default=True)),
                ('createdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PB_GV',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('gv', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.gv')),
                ('phongban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='homepage.phongban')),
            ],
        ),
    ]
