# Generated by Django 4.2.7 on 2024-11-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_gv_phongban_pb_gv'),
    ]

    operations = [
        migrations.AddField(
            model_name='gv',
            name='image_file',
            field=models.ImageField(blank=True, upload_to='image'),
        ),
    ]
