# Generated by Django 4.2.7 on 2024-11-23 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_gv_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gv',
            name='namsinh',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
