# Generated by Django 4.2.7 on 2024-11-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_accounttype_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_picture',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='forget_password_token',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
