# Generated by Django 4.0.6 on 2025-05-27 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0016_postforum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('subjects', models.TextField(help_text='Danh sách môn học, cách nhau bởi dấu phẩy')),
            ],
        ),
        migrations.CreateModel(
            name='AdmissionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=10)),
                ('ethnicity', models.CharField(max_length=50)),
                ('birthday', models.DateField()),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('cccd_province', models.CharField(max_length=100)),
                ('cccd_district', models.CharField(max_length=100)),
                ('cccd_ward', models.CharField(max_length=100)),
                ('cccd_town', models.CharField(max_length=255)),
                ('hometown_province', models.CharField(max_length=100)),
                ('birth_reg_province', models.CharField(max_length=100)),
                ('birth_reg_district', models.CharField(max_length=100)),
                ('birth_reg_ward', models.CharField(max_length=100)),
                ('birth_reg_town', models.CharField(max_length=255)),
                ('birth_place_province', models.CharField(max_length=100)),
                ('birth_place_district', models.CharField(max_length=100)),
                ('birth_place_ward', models.CharField(max_length=100)),
                ('birth_place_facility', models.CharField(max_length=255)),
                ('current_province', models.CharField(max_length=100)),
                ('current_district', models.CharField(max_length=100)),
                ('current_ward', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20)),
                ('id_issued_date', models.CharField(max_length=50)),
                ('id_issued_place', models.CharField(default='Cục trưởng cục cảnh sát QLHC về TTXH', max_length=100)),
                ('graduation_year', models.CharField(max_length=10)),
                ('graduation_school', models.CharField(max_length=255)),
                ('graduation_rank', models.CharField(max_length=50)),
                ('exam_score', models.FloatField(blank=True, null=True)),
                ('conduct', models.CharField(blank=True, max_length=50, null=True)),
                ('avg_score', models.FloatField(blank=True, null=True)),
                ('current_job', models.CharField(blank=True, max_length=255)),
                ('father_name', models.CharField(max_length=255)),
                ('father_job', models.CharField(max_length=100)),
                ('father_birth', models.CharField(max_length=10)),
                ('father_phone', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=255)),
                ('mother_job', models.CharField(max_length=100)),
                ('mother_birth', models.CharField(max_length=10)),
                ('mother_phone', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.campus')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.shift')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.subjectgroup')),
            ],
        ),
        migrations.CreateModel(
            name='CampusShiftGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_count', models.PositiveIntegerField(default=0)),
                ('number_of_classes', models.PositiveIntegerField(default=0)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.campus')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.shift')),
                ('subject_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.subjectgroup')),
            ],
            options={
                'unique_together': {('campus', 'shift', 'subject_group')},
            },
        ),
    ]
