# Generated by Django 4.0.6 on 2025-06-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_admissionform_email_admissionform_enable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='cccd_image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Ảnh CCCD'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='school_record_image',
            field=models.ImageField(blank=True, null=True, upload_to='image', verbose_name='Ảnh học bạ'),
        ),
    ]
