# Generated by Django 4.0.6 on 2025-06-13 15:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_admissionform_cccd_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='literature_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='math_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
