# Generated by Django 4.0.6 on 2025-06-25 13:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_admissionform_literature_score_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admissionform',
            name='exam_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)]),
        ),
    ]
