# Generated by Django 4.0.6 on 2025-06-30 12:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0021_alter_admissionform_exam_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='admissionform',
            name='literature_score_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Văn lớp 6'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='literature_score_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Văn lớp 7'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='literature_score_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Văn lớp 8'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='literature_score_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Văn lớp 9'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='math_score_6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Toán lớp 6'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='math_score_7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Toán lớp 7'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='math_score_8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Toán lớp 8'),
        ),
        migrations.AddField(
            model_name='admissionform',
            name='math_score_9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Điểm Toán lớp 9'),
        ),
    ]
