# Generated by Django 5.1.6 on 2026-01-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0022_admissionform_literature_score_6_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "student_code",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã học viên",
                    ),
                ),
                ("class_name", models.CharField(max_length=50, verbose_name="Lớp")),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                ("birthday", models.DateField(verbose_name="Ngày sinh")),
                ("id_number", models.CharField(max_length=20, verbose_name="Số CCCD")),
                (
                    "birth_place",
                    models.CharField(max_length=255, verbose_name="Nơi sinh"),
                ),
                ("ethnicity", models.CharField(max_length=50, verbose_name="Dân tộc")),
                ("gender", models.CharField(max_length=10, verbose_name="Giới tính")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homepage.campus",
                        verbose_name="Cơ sở",
                    ),
                ),
                (
                    "subject_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homepage.subjectgroup",
                        verbose_name="Tổ hợp môn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học viên",
                "verbose_name_plural": "Học viên",
            },
        ),
        migrations.CreateModel(
            name="StudentExamRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "phone",
                    models.CharField(max_length=20, verbose_name="Số điện thoại"),
                ),
                (
                    "exam_subjects",
                    models.JSONField(
                        help_text="Danh sách các môn học viên đã chọn",
                        verbose_name="Môn thi tốt nghiệp",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.student",
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Đăng ký thi tốt nghiệp",
                "verbose_name_plural": "Đăng ký thi tốt nghiệp",
            },
        ),
    ]
