# Generated by Django 5.1.6 on 2026-01-09 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0023_student_studentexamregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="address",
            field=models.TextField(
                blank=True, null=True, verbose_name="Địa chỉ thường trú"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(
                blank=True, max_length=254, null=True, verbose_name="Email"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="note",
            field=models.TextField(blank=True, null=True, verbose_name="Ghi chú"),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Họ tên phụ huynh"
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_phone",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                verbose_name="Số điện thoại phụ huynh",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Số điện thoại"
            ),
        ),
        migrations.AddField(
            model_name="studentexamregistration",
            name="registration_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Ngày đăng ký cuối cùng",
                null=True,
                verbose_name="Ngày đăng ký",
            ),
        ),
        migrations.AddField(
            model_name="studentexamregistration",
            name="update_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Số lần học viên đã cập nhật thông tin đăng ký",
                verbose_name="Số lần cập nhật",
            ),
        ),
        migrations.AlterField(
            model_name="studentexamregistration",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="Học viên có thể điền sau",
                max_length=254,
                null=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="studentexamregistration",
            name="exam_subjects",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Danh sách các môn học viên đã chọn",
                verbose_name="Môn thi tốt nghiệp",
            ),
        ),
        migrations.AlterField(
            model_name="studentexamregistration",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Học viên có thể điền sau",
                max_length=20,
                null=True,
                verbose_name="Số điện thoại",
            ),
        ),
        migrations.CreateModel(
            name="RegistrationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email cũ"
                    ),
                ),
                (
                    "old_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại cũ",
                    ),
                ),
                (
                    "old_exam_subjects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Môn thi tốt nghiệp cũ"
                    ),
                ),
                (
                    "new_email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email mới"
                    ),
                ),
                (
                    "new_phone",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Số điện thoại mới",
                    ),
                ),
                (
                    "new_exam_subjects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Môn thi tốt nghiệp mới"
                    ),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("created", "Đăng ký lần đầu"),
                            ("updated", "Cập nhật thông tin"),
                        ],
                        default="updated",
                        max_length=20,
                        verbose_name="Loại hành động",
                    ),
                ),
                (
                    "update_count",
                    models.PositiveIntegerField(
                        verbose_name="Số lần cập nhật tại thời điểm này"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Thời gian cập nhật"
                    ),
                ),
                (
                    "registration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="homepage.studentexamregistration",
                        verbose_name="Đăng ký",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử đăng ký",
                "verbose_name_plural": "Lịch sử đăng ký",
                "ordering": ["-created_at"],
            },
        ),
    ]
