# Generated by Django 5.1.6 on 2026-03-18 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0024_student_address_student_email_student_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, verbose_name="Tên phòng (vd: P101)"
                    ),
                ),
                ("row_count", models.PositiveIntegerField(verbose_name="Số hàng")),
                (
                    "col_count",
                    models.PositiveIntegerField(
                        verbose_name="Số cột (số ghế mỗi hàng)"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.campus",
                        verbose_name="Cơ sở",
                    ),
                ),
            ],
            options={
                "verbose_name": "Phòng thi",
                "verbose_name_plural": "Phòng thi",
                "unique_together": {("campus", "name")},
            },
        ),
        migrations.CreateModel(
            name="ExamRoomStudent",
            fields=[
                (
                    "student_code",
                    models.CharField(
                        max_length=7,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Mã học viên",
                    ),
                ),
                ("class_name", models.CharField(max_length=50, verbose_name="Lớp")),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                (
                    "exam_number",
                    models.CharField(
                        blank=True,
                        max_length=6,
                        null=True,
                        unique=True,
                        verbose_name="Số báo danh",
                    ),
                ),
                (
                    "is_integration",
                    models.BooleanField(
                        default=False, verbose_name="Học viên hoà nhập"
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homepage.campus",
                        verbose_name="Cơ sở",
                    ),
                ),
                (
                    "subject_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="homepage.subjectgroup",
                        verbose_name="Tổ hợp môn",
                    ),
                ),
            ],
            options={
                "verbose_name": "Học viên (xếp phòng thi)",
                "verbose_name_plural": "Học viên (xếp phòng thi)",
            },
        ),
        migrations.CreateModel(
            name="ExamRoomSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("sang", "Sáng"), ("chieu", "Chiều"), ("toi", "Tối")],
                        default="sang",
                        max_length=10,
                        verbose_name="Ca thi",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="Môn thi"),
                ),
                (
                    "exam_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.examroom",
                        verbose_name="Phòng thi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Môn thi phòng thi",
                "verbose_name_plural": "Môn thi phòng thi",
                "unique_together": {("exam_room", "shift", "subject_name")},
            },
        ),
        migrations.CreateModel(
            name="ExamSubjectSeat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("sang", "Sáng"), ("chieu", "Chiều"), ("toi", "Tối")],
                        default="sang",
                        max_length=10,
                        verbose_name="Ca thi",
                    ),
                ),
                (
                    "subject_name",
                    models.CharField(max_length=100, verbose_name="Môn thi"),
                ),
                ("seat_number", models.PositiveIntegerField(verbose_name="Số ghế")),
                (
                    "exam_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.examroom",
                        verbose_name="Phòng thi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.examroomstudent",
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sơ đồ ghế theo môn",
                "verbose_name_plural": "Sơ đồ ghế theo môn",
                "unique_together": {
                    ("exam_room", "shift", "subject_name", "seat_number"),
                    ("exam_room", "shift", "subject_name", "student"),
                },
            },
        ),
        migrations.CreateModel(
            name="StudentExamAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("sang", "Sáng"), ("chieu", "Chiều"), ("toi", "Tối")],
                        default="sang",
                        max_length=10,
                        verbose_name="Ca thi",
                    ),
                ),
                (
                    "seat_number",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Số ghế"
                    ),
                ),
                (
                    "exam_room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="homepage.examroom",
                        verbose_name="Phòng thi",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="homepage.examroomstudent",
                        verbose_name="Học viên (xếp phòng)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xếp phòng thi",
                "verbose_name_plural": "Xếp phòng thi",
                "unique_together": {("student", "shift")},
            },
        ),
    ]
