# Generated by Django 5.1.6 on 2026-03-24 02:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0025_examroom_examroomstudent_examroomsubject_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentInfoRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student_code",
                    models.CharField(
                        max_length=30, unique=True, verbose_name="Mã học viên"
                    ),
                ),
                (
                    "stt",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="STT gốc từ Excel"
                    ),
                ),
                (
                    "class_name",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Lớp"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Họ và tên"
                    ),
                ),
                (
                    "birthday",
                    models.DateField(blank=True, null=True, verbose_name="Ngày sinh"),
                ),
                (
                    "birth_place",
                    models.CharField(
                        blank=True, default="", max_length=255, verbose_name="Nơi sinh"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Giới tính"
                    ),
                ),
                (
                    "ethnicity",
                    models.CharField(
                        blank=True, default="", max_length=50, verbose_name="Dân tộc"
                    ),
                ),
                (
                    "id_number",
                    models.CharField(
                        blank=True, default="", max_length=20, verbose_name="Số CCCD"
                    ),
                ),
                (
                    "contact_address",
                    models.TextField(
                        blank=True, default="", verbose_name="Địa chỉ liên hệ"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Gmail"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=20,
                        verbose_name="Số điện thoại",
                    ),
                ),
                (
                    "highschool_10",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nơi học THPT lớp 10",
                    ),
                ),
                (
                    "highschool_11",
                    models.CharField(
                        blank=True,
                        default="",
                        max_length=255,
                        verbose_name="Nơi học THPT lớp 11",
                    ),
                ),
                (
                    "exam_subjects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="Môn thi TN THPT"
                    ),
                ),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Thông tin học viên kiểm tra",
                "verbose_name_plural": "Thông tin học viên kiểm tra",
                "ordering": ["class_name", "full_name"],
            },
        ),
        migrations.CreateModel(
            name="StudentInfoVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "class_name_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "full_name_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "birthday_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "birth_place_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "gender_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "ethnicity_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "id_number_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "contact_address_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "email_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "phone_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "highschool_10_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "highschool_11_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "exam_subjects_status",
                    models.CharField(
                        blank=True,
                        choices=[("", "Chưa chọn"), ("D", "Đúng"), ("S", "Sai")],
                        default="",
                        max_length=1,
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True, null=True, verbose_name="Ghi chú của học viên"
                    ),
                ),
                (
                    "submit_count",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Tối đa 2 lần; sau đó chỉ xem, không chỉnh sửa.",
                        verbose_name="Số lần đã gửi xác nhận",
                    ),
                ),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="verification",
                        to="homepage.studentinforecord",
                        verbose_name="Học viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Xác nhận thông tin học viên",
                "verbose_name_plural": "Xác nhận thông tin học viên",
            },
        ),
        migrations.CreateModel(
            name="StudentInfoVerificationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "submit_index",
                    models.PositiveSmallIntegerField(verbose_name="Lần gửi thứ"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payload",
                    models.JSONField(default=dict, verbose_name="Dữ liệu đã gửi"),
                ),
                (
                    "verification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history_entries",
                        to="homepage.studentinfoverification",
                        verbose_name="Bản xác nhận",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lịch sử gửi xác nhận",
                "verbose_name_plural": "Lịch sử gửi xác nhận",
                "ordering": ["-created_at"],
            },
        ),
    ]
