# Generated by Django 5.1.6 on 2026-04-14 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0026_studentinforecord_studentinfoverification_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostForumComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("author_name", models.CharField(max_length=100)),
                ("body", models.TextField(max_length=2000)),
                ("createdate", models.DateTimeField(auto_now_add=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="homepage.postforumcomment",
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="homepage.postforum",
                    ),
                ),
            ],
            options={
                "ordering": ["createdate"],
            },
        ),
    ]
