# Generated by Django 5.1.6 on 2026-04-18 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepage", "0027_postforumcomment"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamRoomShiftConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "shift",
                    models.CharField(
                        choices=[("sang", "Sáng"), ("chieu", "Chiều"), ("toi", "Tối")],
                        default="sang",
                        max_length=10,
                    ),
                ),
                ("row_count", models.PositiveIntegerField(verbose_name="Số hàng")),
                (
                    "col_count",
                    models.PositiveIntegerField(
                        verbose_name="Số cột (số ghế mỗi hàng)"
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=0, editable=False)),
                (
                    "exam_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shift_configs",
                        to="homepage.examroom",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cấu hình phòng theo ca",
                "verbose_name_plural": "Cấu hình phòng theo ca",
                "unique_together": {("exam_room", "shift")},
            },
        ),
    ]
