# Generated by Django 5.1.3 on 2026-05-22 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0040_admissionform_id_number_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSort2Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='Mã điểm thi')),
                ('name', models.CharField(max_length=255, verbose_name='Tên điểm thi')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='STT')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Điểm thi (SXPT II)',
                'verbose_name_plural': 'Điểm thi (SXPT II)',
                'ordering': ['sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='ExamSort2Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Họ và tên')),
                ('class_name', models.CharField(max_length=50, verbose_name='Lớp')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='homepage.campus', verbose_name='Thuộc cơ sở')),
            ],
            options={
                'verbose_name': 'Thí sinh (SXPT II)',
                'verbose_name_plural': 'Thí sinh (SXPT II)',
                'ordering': ['campus__code', 'class_name', 'full_name'],
            },
        ),
        migrations.CreateModel(
            name='ExamSort2Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tên phòng thi')),
                ('col_count', models.PositiveIntegerField(verbose_name='Số cột')),
                ('row_count', models.PositiveIntegerField(verbose_name='Số hàng')),
                ('capacity', models.PositiveIntegerField(default=0, editable=False)),
                ('target_campus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exam_sort2_target_rooms', to='homepage.campus', verbose_name='Đối tượng cơ sở')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='homepage.examsort2venue')),
            ],
            options={
                'verbose_name': 'Phòng thi (SXPT II)',
                'verbose_name_plural': 'Phòng thi (SXPT II)',
                'ordering': ['name'],
                'unique_together': {('venue', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ExamSort2VenueCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_links', to='homepage.examsort2candidate')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_candidates', to='homepage.examsort2venue')),
            ],
            options={
                'verbose_name': 'Thí sinh tại điểm thi',
                'verbose_name_plural': 'Thí sinh tại điểm thi',
                'unique_together': {('venue', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='ExamSort2SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.PositiveIntegerField(verbose_name='Số ghế')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='homepage.examsort2room')),
                ('venue_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seat_assignments', to='homepage.examsort2venuecandidate')),
            ],
            options={
                'verbose_name': 'Xếp ghế (SXPT II)',
                'verbose_name_plural': 'Xếp ghế (SXPT II)',
                'ordering': ['seat_number'],
                'unique_together': {('room', 'seat_number'), ('room', 'venue_candidate')},
            },
        ),
    ]
