# Generated by Django 5.1.3 on 2026-05-22 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0041_exam_sort2'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsort2candidate',
            name='elective_subject_1',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Môn tự chọn 1'),
        ),
        migrations.AddField(
            model_name='examsort2candidate',
            name='elective_subject_2',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Môn tự chọn 2'),
        ),
    ]
