# Generated by Django 5.1.6 on 2026-02-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("homepage", "0024_student_address_student_email_student_note_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=10, unique=True, verbose_name="Mã"),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="Tên"),
                ),
            ],
            options={
                "verbose_name": "Điểm liên kết",
                "verbose_name_plural": "Điểm liên kết",
            },
        ),
        migrations.CreateModel(
            name="ScheduleVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200,
                        verbose_name="Tên phiên bản (vd: T2/2025 Tuần 1)",
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(blank=True, null=True, verbose_name="Áp dụng từ"),
                ),
                (
                    "effective_to",
                    models.DateField(blank=True, null=True, verbose_name="Áp dụng đến"),
                ),
                (
                    "year",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Năm"
                    ),
                ),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tháng (1-12)"
                    ),
                ),
                (
                    "week",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Tuần trong tháng (1-4)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Ngày tạo"),
                ),
            ],
            options={
                "verbose_name": "Phiên bản TKB",
                "verbose_name_plural": "Phiên bản TKB",
                "ordering": ["-year", "-month", "-week"],
            },
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                (
                    "teacher_code",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Mã giáo viên"
                    ),
                ),
                (
                    "display_subject",
                    models.CharField(
                        blank=True,
                        help_text="Hiển thị ở cột Môn trong bảng chấm công",
                        max_length=100,
                        verbose_name="Tên môn (từ DSGV)",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giáo viên",
                "verbose_name_plural": "Giáo viên",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="ClassRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Tên lớp")),
                (
                    "grade",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(10, "10"), (11, "11"), (12, "12")],
                        null=True,
                        verbose_name="Khối",
                    ),
                ),
                (
                    "class_size",
                    models.PositiveIntegerField(default=0, verbose_name="Sĩ số"),
                ),
                (
                    "managing_campus",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_classrooms",
                        to="homepage.campus",
                        verbose_name="Cơ sở quản lý",
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="classrooms_at_location",
                        to="adminpage.location",
                        verbose_name="Điểm liên kết",
                    ),
                ),
            ],
            options={
                "verbose_name": "Lớp học",
                "verbose_name_plural": "Lớp học",
                "ordering": ["grade", "name"],
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "day_of_week",
                    models.PositiveSmallIntegerField(
                        help_text="2=Thứ 2, 3=Thứ 3, ... 8=Chủ nhật", verbose_name="Thứ"
                    ),
                ),
                ("period", models.PositiveSmallIntegerField(verbose_name="Tiết")),
                (
                    "subject_name",
                    models.CharField(
                        max_length=50, verbose_name="Tên môn (vd: SH để lọc Sinh hoạt)"
                    ),
                ),
                (
                    "session",
                    models.CharField(
                        choices=[("sang", "Sáng"), ("chieu", "Chiều"), ("toi", "Tối")],
                        default="sang",
                        max_length=10,
                        verbose_name="Buổi",
                    ),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Ngày áp dụng"
                    ),
                ),
                (
                    "classroom",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="adminpage.classroom",
                        verbose_name="Lớp",
                    ),
                ),
                (
                    "version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="adminpage.scheduleversion",
                        verbose_name="Phiên bản TKB",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="adminpage.teacher",
                        verbose_name="Giáo viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tiết TKB",
                "verbose_name_plural": "Tiết TKB",
                "ordering": ["day_of_week", "period"],
            },
        ),
        migrations.CreateModel(
            name="AttendanceOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
                (
                    "value",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Số tiết (đã sửa)"
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_overrides",
                        to="adminpage.teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ghi đè tiết chấm công",
                "verbose_name_plural": "Ghi đè tiết chấm công",
                "unique_together": {("teacher", "year", "month", "day")},
            },
        ),
    ]
