# Generated by Django 5.1.6 on 2026-02-23 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JournalClass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Tên lớp"
                    ),
                ),
            ],
            options={
                "verbose_name": "Lớp (Sổ đầu bài)",
                "verbose_name_plural": "Lớp (Sổ đầu bài)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="JournalRow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "row_order",
                    models.PositiveIntegerField(
                        help_text="STT trong bảng", verbose_name="Thứ tự hàng"
                    ),
                ),
            ],
            options={
                "verbose_name": "Hàng sổ đầu bài",
                "verbose_name_plural": "Hàng sổ đầu bài",
                "ordering": ["row_order"],
            },
        ),
        migrations.CreateModel(
            name="JournalTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=255, verbose_name="Họ và tên"),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="Môn")),
                (
                    "access_code",
                    models.CharField(
                        help_text="Giáo viên nhập mã này để vào sổ đầu bài",
                        max_length=50,
                        unique=True,
                        verbose_name="Mã số truy cập",
                    ),
                ),
                (
                    "num_classes",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Số hàng trong sổ = Số lớp × 2",
                        verbose_name="Số lớp",
                    ),
                ),
            ],
            options={
                "verbose_name": "Giáo viên (Sổ đầu bài)",
                "verbose_name_plural": "Giáo viên (Sổ đầu bài)",
                "ordering": ["full_name"],
            },
        ),
        migrations.CreateModel(
            name="SchoolConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current_date", models.DateField(verbose_name="Ngày hiện tại")),
                (
                    "current_week",
                    models.PositiveSmallIntegerField(verbose_name="Tuần học hiện tại"),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Cấu hình trường (Legacy)",
                "verbose_name_plural": "Cấu hình trường (Legacy)",
            },
        ),
        migrations.CreateModel(
            name="JournalEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("week_number", models.PositiveSmallIntegerField(verbose_name="Tuần")),
                ("lesson_date", models.DateField(verbose_name="Ngày dạy")),
                (
                    "period",
                    models.PositiveSmallIntegerField(
                        help_text="1-5", verbose_name="Tiết dạy"
                    ),
                ),
                (
                    "classes_taught",
                    models.CharField(
                        blank=True,
                        help_text="Lớp hoặc nhiều lớp cách nhau bằng dấu phẩy",
                        max_length=255,
                        verbose_name="Lớp dạy",
                    ),
                ),
                (
                    "student_count",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="Sĩ số"
                    ),
                ),
                (
                    "absent_students",
                    models.TextField(blank=True, verbose_name="Học viên vắng"),
                ),
                (
                    "lesson_title",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Tên bài giảng"
                    ),
                ),
                (
                    "comment",
                    models.TextField(
                        blank=True, verbose_name="Nhận xét của GV sau tiết dạy"
                    ),
                ),
                (
                    "journal_row",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="adminpage.journalrow",
                        verbose_name="Hàng",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ô sổ đầu bài",
                "verbose_name_plural": "Ô sổ đầu bài",
                "ordering": ["-lesson_date", "-id"],
            },
        ),
        migrations.AddField(
            model_name="journalrow",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="journal_rows",
                to="adminpage.journalteacher",
                verbose_name="Giáo viên",
            ),
        ),
        migrations.CreateModel(
            name="ClassJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lesson_date", models.DateField()),
                ("week", models.PositiveSmallIntegerField()),
                ("period", models.PositiveSmallIntegerField(default=1)),
                ("subject", models.CharField(blank=True, max_length=100)),
                ("lesson_title", models.CharField(blank=True, max_length=500)),
                ("absent_students", models.TextField(blank=True)),
                ("rating", models.CharField(blank=True, max_length=20)),
                ("completed", models.BooleanField(default=False)),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legacy_entries",
                        to="adminpage.journalteacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sổ đầu bài (Legacy)",
            },
        ),
        migrations.CreateModel(
            name="SubjectJournal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50, verbose_name="Môn")),
                ("year", models.PositiveIntegerField(verbose_name="Năm học")),
                (
                    "week1_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Khi set, tự động tạo 13 tuần liền kề",
                        null=True,
                        verbose_name="Ngày bắt đầu tuần 1",
                    ),
                ),
            ],
            options={
                "verbose_name": "Sổ đầu bài (theo môn/năm)",
                "verbose_name_plural": "Sổ đầu bài (theo môn/năm)",
                "ordering": ["-year", "subject"],
                "unique_together": {("subject", "year")},
            },
        ),
        migrations.AddField(
            model_name="journalrow",
            name="subject_journal",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rows",
                to="adminpage.subjectjournal",
                verbose_name="Sổ đầu bài",
            ),
        ),
        migrations.CreateModel(
            name="JournalWeek",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "week_number",
                    models.PositiveSmallIntegerField(
                        help_text="1-13", verbose_name="Tuần"
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Từ ngày")),
                ("end_date", models.DateField(verbose_name="Đến ngày")),
                ("is_locked", models.BooleanField(default=False, verbose_name="Khóa")),
                (
                    "allow_late_edit",
                    models.BooleanField(
                        default=False,
                        help_text="Bật khi quản trị viên mở lại tuần đã quá hạn.",
                        verbose_name="Cho phép nhập/sửa quá hạn",
                    ),
                ),
                (
                    "subject_journal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weeks",
                        to="adminpage.subjectjournal",
                        verbose_name="Sổ đầu bài",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuần sổ đầu bài",
                "verbose_name_plural": "Tuần sổ đầu bài",
                "ordering": ["week_number"],
                "unique_together": {("subject_journal", "week_number")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="journalrow",
            unique_together={("subject_journal", "row_order")},
        ),
    ]
