# Generated by Django 5.1.6 on 2026-03-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "adminpage",
            "0002_journalclass_journalrow_journalteacher_schoolconfig_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceExcludedDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("month", models.PositiveSmallIntegerField()),
                ("day", models.PositiveSmallIntegerField()),
            ],
            options={
                "verbose_name": "Ngày không chấm công",
                "verbose_name_plural": "Ngày không chấm công",
                "unique_together": {("year", "month", "day")},
            },
        ),
    ]
