# Generated by Django 5.1.6 on 2026-06-05 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adminpage", "0003_attendanceexcludedday"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journalweek",
            name="week_number",
            field=models.PositiveSmallIntegerField(
                help_text="Số thứ tự tuần (1, 2, 3, …)", verbose_name="Tuần"
            ),
        ),
        migrations.CreateModel(
            name="JournalTeacherWeekLimitOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allow_over_limit",
                    models.BooleanField(
                        default=False,
                        help_text="Bật lên để giáo viên có thể nhập thêm tiết trong tuần (vượt quá số hàng của giáo viên).",
                        verbose_name="Cho phép vượt giới hạn số tiết",
                    ),
                ),
                (
                    "journal_week",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teacher_limit_overrides",
                        to="adminpage.journalweek",
                        verbose_name="Tuần sổ đầu bài",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="week_limit_overrides",
                        to="adminpage.journalteacher",
                        verbose_name="Giáo viên",
                    ),
                ),
            ],
            options={
                "verbose_name": "Override giới hạn tiết theo tuần (GV)",
                "verbose_name_plural": "Override giới hạn tiết theo tuần (GV)",
                "unique_together": {("journal_week", "teacher")},
            },
        ),
    ]
